language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install nose coverage BeautifulSoup4
script:
  - nosetests --with-coverage
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
