"""add height, width and size to stored_file

Revision ID: 555bc8d5cbd7
Revises: 2d5db2a698f6
Create Date: 2013-06-06 14:43:26.622689

"""

# revision identifiers, used by Alembic.
revision = '555bc8d5cbd7'
down_revision = '2d5db2a698f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_file', sa.Column('width', sa.Integer(), default=0, nullable=True))
    op.add_column('stored_file', sa.Column('size', sa.BigInteger(), default=0, nullable=False))
    op.add_column('stored_file', sa.Column('height', sa.Integer(), default=0, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stored_file', 'height')
    op.drop_column('stored_file', 'size')
    op.drop_column('stored_file', 'width')
    ### end Alembic commands ###
