"""StoredFile.no_previews

Revision ID: 5a1014061968
Revises: 1036f2d710dc
Create Date: 2013-12-30 22:40:09.773656

"""

# revision identifiers, used by Alembic.
revision = '5a1014061968'
down_revision = '1036f2d710dc'

from alembic import op
import sqlalchemy as sa

from imgee.models import StoredFile


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_file', sa.Column('no_previews', sa.Boolean(), nullable=True))
    ### end Alembic commands ###
    connection = op.get_bind()
    sf = StoredFile.__table__
    connection.execute(sf.update().values(no_previews=False))

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stored_file', 'no_previews')
    ### end Alembic commands ###
